# Generated by Django 2.2.6 on 2019-10-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('num_regex', models.CharField(max_length=50)),
                ('polis_type', models.CharField(choices=[('OMS', 'OMS'), ('DMS', 'DMS')], default='OMS', max_length=3)),
            ],
        ),
    ]
