# Generated by Django 2.2.6 on 2019-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polischeck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polis_ltd_prefix', models.CharField(max_length=50)),
                ('local_polis_search', models.IntegerField(default=0)),
                ('polis_ltd_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='polis',
            name='BILLING',
            field=models.IntegerField(default=0),
        ),
    ]
