# Generated by Django 2.2.6 on 2019-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polischeck', '0002_auto_20191022_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundPolis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf_polis_regex', models.CharField(max_length=50)),
                ('nf_company_name', models.CharField(max_length=255)),
                ('nf_polis_type', models.CharField(choices=[('OMS', 'OMS'), ('DMS', 'DMS')], default='OMS', max_length=3)),
                ('local_polis_search', models.IntegerField(default=1)),
                ('polis_req_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LocalBase',
        ),
    ]
