# Generated by Django 2.2.6 on 2019-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polischeck', '0003_auto_20191022_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotFoundPolis',
        ),
        migrations.AddField(
            model_name='polis',
            name='not_found_search',
            field=models.IntegerField(default=0),
        ),
    ]
