# Generated by Django 2.2.6 on 2019-10-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polischeck', '0004_auto_20191023_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polis',
            old_name='company_name',
            new_name='company',
        ),
    ]
